# Підключення необхідних бібліотек та файлів
require 'yaml'
require 'json'
require 'pathname'
require_relative 'quiz_manager'
require_relative 'project_config'
require_relative 'quiz_question'
require_relative 'question_data_manager'
require_relative 'data_writer'
require_relative 'data_reader'
require_relative 'data_statistics'
require_relative 'core_engine'